export const accountSelect = "#accountSelect";
export const accountName = ".ng-binding:nth-child(1)"
export const accountNumber = ".ng-binding:nth-child(1)";
export const accountBalance = ".ng-binding:nth-child(2)";
export const accountCurrency = ".ng-binding:nth-child(3)";
export const buttonTransactionsMenu = ".btn.tab:contains('Transactions')";
export const buttonDepositMenu = ".btn.tab:contains('Deposit')";
export const buttonWithdrawlMenu = ".btn.tab:contains('Withdrawl')";
export const labelDepositWithDrawl = "label";
export const inputDepositWithDrawl = "input[ng-model='amount']"
export const buttonSubmitDepositWithDrawl = "button[type=submit]";
export const messageSubmitDepositWithDrawl = "span[ng-show='message']"