export const websiteTitle = 'XYZ Bank'
export const customerLoginMenu = '.btn-primary:contains("Customer Login")'
export const loginModalLabel = 'label'
export const loginUsernameDropdown = '#userSelect'
export const selectUsername = '.ng-binding:contains("Hermoine Granger")'
export const loginButton = '.btn-default:contains("Login")'
export const bankManagerLogin = '.btn-primary:contains("Bank Manager Login")'